const UserModel = require("../Models/UserModel");
const otp_generator = require("otp-generator"); //npm optGenrator Library
const bcrypt = require("bcrypt");
const sendEmail = require("../email services/email");
const jwt = require("jsonwebtoken");
const register = async (req, res) => {
  try {
    console.log(req.body);
    const email = req.body.email;

    //cheking for existing user
    const isUserExisting = await UserModel.findOne({ email: email });
    if (isUserExisting) {
      console.log("user Aready exist");

      return res
        .status(400)
        .json({ message: `Bad request ${email} already exist.` });
    }

    //verification token is generated
    const verificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    // Expiry of otp genrator is created
    const expires = new Date();
    expires.setMinutes(expires.getMinutes() + 5);

    //Encription of password
    const hashPassword = await bcrypt.hash(req.body.password, 10);

    //New User Created
    const newUser = await UserModel({
      email: req.body.email,
      username: req.body.username,
      password: hashPassword, //Encript password
      verificationToken: {
        token: verificationToken,
        expires: expires,
      },
    });
    console.log(newUser);
    await newUser.save();

    const emailBody = `<p>Please Click on the link to Verify Your Account. <b>https://mern-auth-drtd.onrender.com/user/verify/${verificationToken}</b></p>`;
    const subject = "Verification Email";

    await sendEmail(req.body.email, subject, emailBody);

    res.json({ message: "Verification link send to your email!" });
  } catch (error) {
    res.json({ message: "Something went wrong!" });
  }
};

//Verify through user Emial
const verifyUser = async (req, res) => {
  try {
    console.log(req.params);
    const { token } = req.params;
    const isTokenValid = await UserModel.findOne({
      "verificationToken.token": token,
      "verificationToken.expires": { $gt: new Date() },
    });
    console.log(isTokenValid);

    if (!isTokenValid) {
      return res
        .status(400)
        .send(
          `<p>Token Invalid or Expires</p> <a href="https://mern-auth-drtd.onrender.com/user/resndVerification/${token}">Resend Verification Mail</a>`,
        );
    }
    if (isTokenValid.isVerified) {
      return res.send("Accound Already Verified, Please login");
    }
    isTokenValid.isVerified = true;
    await isTokenValid.save();
    res.send("Account Verified Successfully");
  } catch (error) {
    res.send("Something went wrong!");
    console.error(error);
  }
};
const resndVerification = async (req, res) => {
  try {
    const { token } = req.params;
    const user = await UserModel.findOne({
      "verificationToken.token": token,
      isVerified: false,
    });
    if (!user) {
      return res.status(400).send(`<p>User not found OR already verified.</p>`);
    }
    //verification token is generated
    const newVerificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    // Expiry of otp genrator is created
    const expires = new Date();
    expires.setMinutes(expires.getMinutes() + 5);

    user.verificationToken = {
      expires: expires,
      token: newVerificationToken,
    };
    await user.save();

    const emailBody = `<p>Please Click on the link to Verify Your Account. <b>https://mern-auth-drtd.onrender.com/user/verify/${newVerificationToken}</b></p>`;
    const subject = "Verification Email";

    await sendEmail(user.email, subject, emailBody);

    res.send("Please Check your email for new Verification Link");
  } catch (error) {
    console.error(error);
    res.send("Something went wrong");
  }
};

//Login Deatails
const login = async (req, res) => {
  try {
    console.log(req.body);
    const email = req.body.email;
    const isUserExisting = await UserModel.findOne({ email: email });
    if (!isUserExisting) {
      if (req.body.autoGenerated) {
        const password =
          otp_generator.generate(8, {
            upperCaseAlphabets: true,
            lowerCaseAlphabets: true,
            digits: true,
            specialChars: true,
          }) + "&2cA"; //Concatinate in Autogenerated password for safety.
        // console.log(password);
        // return;
        const hashedPassword = await bcrypt.hash(password, 10);
        //New User Created
        const newUser = await UserModel({
          email: email,
          username: req.body.username,
          password: hashedPassword,
          isVerified: true,
        });
        console.log(newUser);
        await newUser.save();
        const jwtPayload = {
          id: newUser._id,
        };
        //Token Has been created
        const token = jwt.sign(jwtPayload, process.env.JWT_SECRET, {
          expiresIn: "12h", //5m
        });

        const emailBody = `<p>Account Created Successfully. Your password is <b>${password}</b> Please Changed it.</p>`;
        const subject = "Account Created via Social";

        await sendEmail(email, subject, emailBody);
        return res.status(200).json({ message: "Logged in Via Social", token });
      }
      return res.status(400).json({ message: `User with ${email} dont exist` });
    }
    if (!isUserExisting.isVerified) {
      return res.status(400).json({
        message: "User not verified, please click the link in email to verify.",
      });
    }
    const password = req.body.password;
    const isPasswordCorrect = await bcrypt.compare(
      password,
      isUserExisting.password,
    );
    if (!isPasswordCorrect) {
      return res
        .status(400)
        .json({ message: "Invalid credential or password" });
    }

    // JWT
    //store user ID in jwtPayload
    const jwtPayload = {
      id: isUserExisting._id,
    };
    //Token Has been created
    const token = jwt.sign(jwtPayload, process.env.JWT_SECRET, {
      expiresIn: "12h",
    });
    console.log(token);

    //token has been send in response
    res.status(200).json({
      message: `login Successfully ${isUserExisting.username}`,
      token,
    });
  } catch (error) {
    res.status(500).json({ message: "Something went wrong" });
    console.error(error);
  }
};

const updateUser = async (req, res) => {
  try {
    const { id } = req.decodedData;
    const { type, newUserData } = req.body;

    const user = await UserModel.findById(id);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    let subject = "";
    let emailBody = "";

    switch (type) {
      case "username":
        user.username = newUserData.username;
        subject = "Username Updated";
        emailBody = "<p>Username Updated Successfully</p>";
        break;

      case "email":
        user.email = newUserData.email;
        subject = "Email Updated";
        emailBody = "<p>Email Updated Successfully</p>";
        break;

      case "password":
        user.password = await bcrypt.hash(newUserData.password, 10);
        subject = "Password Updated";
        emailBody = "<p>Password Updated Successfully</p>";
        break;

      default:
        return res.status(400).json({ message: "Invalid update type" });
    }

    await user.save();

    // 🟡 Email should NOT break the API
    try {
      await sendEmail(user.email, subject, emailBody);
    } catch (emailError) {
      console.error("EMAIL FAILED:", emailError.message);
    }

    res.json({ message: `${type} updated successfully` });
  } catch (error) {
    console.error("UPDATE ERROR:", error);
    res.status(500).json({ message: "Something went wrong" });
  }
};

const forgotPassword = async (req, res) => {
  try {
    console.log(req.body);
    const isUserExisting = await UserModel.findOne({ email: req.body.email });
    if (!isUserExisting) {
      return res
        .status(400)
        .json({ message: `User with ${req.body.email} did not exist.` });
    }
    //Send reset password to existing mail
    if (req.body.isOTPVerified) {
      const hashedPassword = await bcrypt.hash(req.body.password, 10);
      isUserExisting.password = hashedPassword;
      await isUserExisting.save();
      const emailBody = `<p>Your password reset successful.</p>`;
      const subject = `Password Reset Successfully`;
      await sendEmail(isUserExisting.email, subject, emailBody);
      res.status(200).json({ message: "Password Reset Successfully." });
    }
    //verification token is generated
    const verificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    // Expiry of otp genrator is created
    const expires = new Date();

    expires.setMinutes(expires.getMinutes() + 5);
    isUserExisting.OTP_VerificationToken = {
      OTP: verificationToken,
      expires,
    };
    await isUserExisting.save();

    const emailBody = `<p>Your OTP for password reset request is <b>${verificationToken}</b> <br> OTP will expire in 5 minuts`;
    const subject = `Password Reset Email`;
    await sendEmail(isUserExisting.email, subject, emailBody);
    res.status(200).json({ message: "OTP Send Successfully." });
  } catch (error) {
    res.status(500).json({ message: "Something went wrong." });
  }
};

//OTP Verification
const verifyPasswordOTP = async (req, res) => {
  try {
    //get OTP from Body
    const { OTP } = req.body;
    const isOtpValid = await UserModel.findOne({
      "OTP_VerificationToken.OTP": OTP,
      "OTP_VerificationToken.expires": { $gt: new Date() },
    });
    console.log(isOtpValid);
    if (!isOtpValid) {
      res.status(400).json({ message: "OTP Expired" });
      return;
    }
    res.status(200).json({ message: "OTP Verified Successflly" });
  } catch (error) {
    res.status(500).json({ message: "Something went Wrong" });
  }
};

const getUser = async (req, res) => {
  try {
    console.log(req.decodedData);
    const { id } = req.decodedData;
    const data = await UserModel.findById(id);
    console.log(data);
    const user = {
      email: data.email,
      username: data.username,
    };
    res.json({ user: user });
  } catch (error) {
    res.status(500).json({ message: "Something went wrong" });
  }
};

module.exports = {
  register,
  login,
  verifyUser,
  resndVerification,
  updateUser,
  forgotPassword,
  verifyPasswordOTP,
  getUser,
};
