/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link, useNavigate } from "react-router-dom";
import styles from "./login.module.css";
import { useState, type ChangeEvent } from "react";
import { emailRegex, passwordRegex } from "../../utils/Regex";
import toast from "react-hot-toast";
import axios from "axios";
import { GoogleLoginButton } from "react-social-login-buttons";
import { FacebookLoginButton } from "react-social-login-buttons";
import { useGoogleLogin } from "@react-oauth/google";
import Loader from "../Loader/Loader";
import { motion } from "motion/react";
//import { LoginSocialFacebook } from "reactjs-social-login";

const Login = () => {
  const [userDetail, setUserDetail] = useState({
    email: "",
    password: "",
  });

  const [show, setShow] = useState(false);
  const [isLoading, setIsLoading] = useState(false); // loading variable
  const navigate = useNavigate();

  function handleInputChange(event: ChangeEvent<HTMLInputElement>): void {
    //console.log(event.target.value);
    const { name, value } = event.target;
    setUserDetail((prev) => ({
      ...prev,
      [name]: value,
    }));
  }

  const handleLogin = async () => {
    if (!emailRegex.test(userDetail.email)) {
      toast.error("Please enter valid email!");
      return;
    }
    if (!passwordRegex.test(userDetail.password)) {
      toast.error(
        "Password must 8 characters long, Should contain Capital charater, Number, one Special character!",
      );
      return;
    }
    try {
      setIsLoading(true);
      const response = await axios.post(
        `${import.meta.env.VITE_BASE_SERVER_URL}/user/login`,
        userDetail,
      );
      console.log(response);
      toast.success(response.data.message);

      //catching the token from response and stored in LocalStorage
      localStorage.setItem("token", response.data.token);
      navigate("/home");
      setIsLoading(false);
    } catch (error: any) {
      toast.error(error.response.data.message);
      console.error(error);
      setIsLoading(false);
    }
  };
  // handle the Google details to login
  const handleContinueWithGoogle = useGoogleLogin({
    onSuccess: async (response: any) => {
      setIsLoading(true); // ✅ start loader ONLY after success

      try {
        const res = await axios.get(
          "https://www.googleapis.com/oauth2/v3/userinfo",
          {
            headers: {
              Authorization: `Bearer ${response.access_token}`,
            },
          },
        );

        const newUser = {
          username: res.data.name,
          email: res.data.email,
          autoGenerated: true,
        };

        const backendRes = await axios.post(
          `${import.meta.env.VITE_BASE_SERVER_URL}/user/login`,
          newUser,
        );

        toast.success(backendRes.data.message);
        localStorage.setItem("token", backendRes.data.token);
        navigate("/home");
      } catch (error: any) {
        toast.error(error?.response?.data?.message || "Google login failed");
        console.error(error);
      } finally {
        setIsLoading(false); // ✅ ALWAYS stop loader
      }
    },

    onError: () => {
      toast.error("Google login cancelled or failed");
      setIsLoading(false); // ✅ stop loader if popup closed
    },
  });
  return (
    <motion.div
      initial={{ opacity: 0, y: 100 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -50 }}
      transition={{
        type: "spring",
        stiffness: 100,
        damping: 20,
        duration: 0.5,
      }}
      className={styles.container}
    >
      <div className={styles.formContainer}>
        <h2>Login...</h2>

        <div className={styles.social}>
          <div>
            <FacebookLoginButton></FacebookLoginButton>
          </div>
          <div onClick={() => handleContinueWithGoogle()}>
            <GoogleLoginButton></GoogleLoginButton>
          </div>
        </div>
        <div className={styles.inputContainer}>
          <input
            value={userDetail.email}
            name="email"
            type="email"
            placeholder="Enter your email..."
            onChange={handleInputChange}
          />
          <div className={styles.passwordContainer}>
            <input
              value={userDetail.password}
              name="password"
              type={show ? "text" : "password"}
              placeholder="Enter your password..."
              onChange={handleInputChange}
            />
            <button onClick={() => setShow(!show)}>
              {show ? "HIDE" : "SHOW"}
            </button>
          </div>
          <button
            style={{ fontSize: "20px" }}
            disabled={isLoading}
            onClick={handleLogin}
          >
            {isLoading ? <Loader /> : "LOGIN"}
          </button>
        </div>
        <div className={styles.footer}>
          <Link to={"/signup"}>Don't have an Account? SignUp</Link>
          <Link to={"/forget-password"}>Forgot Password</Link>
        </div>
      </div>
    </motion.div>
  );
};

export default Login;
